name: Conditional Label Testing

on:
  push:
    branches:
      - '*'

jobs:
  set_label:
    runs-on: ubuntu-latest
    steps:
      - name: Set label based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "label=main" >> $GITHUB_ENV
          else
            echo "label=testing" >> $GITHUB_ENV
          fi

      - name: Use label
        run: |
          echo "Label value: ${{ env.label }}"
